---

- name: Make sure the transmission vpn container is created and running
  become: yes
  docker_container:
    image: "haugene/transmission-openvpn"
    name: transmission-openvpn
    capabilities:
      - NET_ADMIN
    ports:
      - '9091:9091'
    pull: yes
    networks:
      - name: media_network
    state: started
    env:
      OPENVPN_CONFIG: us-dtw.prod.surfshark.com_udp
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_USERNAME: "{{ vpn_username }}"
      OPENVPN_PASSWORD: "{{ vpn_password }}"
      LOCAL_NETWORK: "192.168.0.0/16,{{ media_subnet }}"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      TRANSMISSION_WEB_UI: transmission-web-control
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "25"
    volumes:
      - "{{ data_root }}/transmission/data:/data"
    restart_policy: unless-stopped
