---
- name: Make sure the transmission  container is created and running
  docker_container:
    image: "ghcr.io/linuxserver/transmission"
    name: transmission
    networks:
      - name: media_network
    ports: # handled by gluetun?
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    pull: yes
    # network_mode: "container:gluetun"
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      # No idea how to actually set these
      TRANSMISSION_WEB_UI: transmission-web-control
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "10"
    volumes:
      - "{{ config_root }}/transmission:/config"
      - "{{ data_root }}/transmission/downloads:/downloads"
    restart_policy: unless-stopped
