---
- hosts: all

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  
  become: true

  roles:
    - role: user_setup
      tags:
        - user_setup
  
    # - role: vpn
    #   tags:
    #     - vpn

    # - role: deluge
    #   tags:
    #     - deluge 

    - role: nfs
      tags:
        - nfs 

    - role: docker
      tags:
        - docker

    # - role: gluetun  
    #   tags:
    #     - gluetun

    - role: nextcloud
      tags:
        - nextcloud

    - role: heimdall  
      tags:
        - heimdall

    - role: jellyfin  
      tags:
        - containers
        - jellyfin

    - role: sonarr  
      tags:
        - containers
        - sonarr

    - role: radarr  
      tags:
        - containers
        - radarr

    - role: portainer  
      tags:
        - containers
        - portainer

    - role: bazarr  
      tags:
        - containers
        - bazarr

    - role: prowlarr  
      tags:
        - prowlarr

    - role: transmission  
      tags:
        - transmission

    - role: plex  
      tags:
        - plex

    # - role: transmission-openvpn 
    #   tags:
    #     - transmission-openvpn

# sonarr if for tv
# radarr is for movies
# filebot renames so jellyfin can serve appropriately (not free)
# utorrent 


# TODO: wire containers through gluetun 

# indexer 

        # TODO: wrap up the media suite and verify that it can be served
        # Store it on nfs mount to  nas
        
        # https://www.fuzzygrim.com/posts/selfhosted-setup
