---
- hosts: all
  become: true

  roles:
    - role: user_setup
      tags:
        - user_setup
  
    - role: docker
      tags:
        - docker

    - role: nfs
      tags:
        - nfs

    - role: nextcloud
      tags:
        - nextcloud

    # - role: nextcloud_2
    #   tags:
    #     - nextcloud_2