---
- hosts: all
  become: true

  roles:
    - role: user_setup
      tags:
        - user_setup
  
    - role: docker
      tags:
        - docker

    - role: nextcloud
      tags:
        - nextcloud