---
- hosts: all
  become: true

  roles:
    - role: user_setup
      tags:
        - user_setup
  
    - role: vpn
      tags:
        - vpn 

    - role: nfs
      tags:
        - nfs 

    - role: docker
      tags:
        - docker

    - role: nextcloud
      tags:
        - nextcloud

    - role: jellyfin
    - role: jellyfin  
      tags:
        - containers
        - jellyfin

    - role: sonarr  
      tags:
        - containers
        - sonarr

    - role: radarr  
      tags:
        - containers
        - radarr

    - role: prowlarr  
      tags:
        - prowlarr

    - role: transmission  
      tags:
        - transmission

# sonarr if for tv
# radarr is for movies
# filebot renames so jellyfin can serve appropriately (not free)
# utorrent 

#deluge


# indexer 

        # TODO: wrap up the media suite and verify that it can be served
        # Store it on nfs mount to  nas
        
        # https://www.fuzzygrim.com/posts/selfhosted-setup
