---
- hosts: all

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  
  become: true

  roles:
    - role: setup/user_setup
      tags:
        - setup
        - user_setup
  
    - role: setup/nfs
      tags:
        - setup
        - nfs 

    - role: setup/docker
      tags:
        - setup
        - docker

    - role: services/nextcloud
      tags:
        - services
        - nextcloud

    - role: heimdall  
      tags:
        - services
        - heimdall

    - role: media/jellyfin  
      tags:
        - media
        - containers
        - jellyfin

    - role: arr/sonarr  
      tags:
        - arr
        - containers
        - sonarr

    - role: arr/radarr  
      tags:
        - arr
        - containers
        - radarr

    - role: arr/lidarr  
      tags:
        - arr
        - containers
        - lidarr

    - role: arr/readarr  
      tags:
        - arr
        - containers
        - readarr

    - role: services/portainer  
      tags:
        - arr
        - containers
        - portainer

    - role: arr/bazarr  
      tags:
        - arr
        - containers
        - bazarr

    - role: arr/prowlarr  
      tags:
        - arr
        - containers
        - prowlarr

    - role: arr/transmission  
      tags:
        - arr
        - containers
        - transmission

    - role: services/vaultwarden  
      tags:
        - services
        - vaultwarden


    # - role: media/plex  
    #   tags:
    #     - media
    #     - plex

    # - role: transmission-openvpn 
    #   tags:
    #     - transmission-openvpn

# TODO: wire containers through gluetun 

# indexer 

        # TODO: wrap up the media suite and verify that it can be served
        # Store it on nfs mount to  nas
        
        # https://www.fuzzygrim.com/posts/selfhosted-setup
