---
- name: Make sure the mealie container is created and running
  docker_container:
    image: hkotel/mealie:latest
    name: mealie
    networks:
      - name: media_network
    ports:
      - "9092:80"
    pull: yes
    state: 'started'
    env:
      # DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # ALLOW_SIGNUP: "false"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ data_root }}/mealie_data:/app/data/"
    restart_policy: unless-stopped

# Username: changeme@email.com
# Password: MyPassword