---
- name: Make sure the heimdall container is created and running
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/heimdall"
    name: "heimdall"
    networks:
      - name: media_network
        ipv4_address: "{{ heimdall_ip }}"
    ports:
      - 49154:80
      - 49155:443
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/heimdall_config:/config"
    restart_policy: unless-stopped
