---
- name: Make sure the heimdall container is created and running
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/heimdall"
    name: "heimdall"
    ports:
      - 49154:80
      - 49155:443
    pull: yes
    state: 'started'
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    #   - TZ=Europe/Madrid
    volumes:
      - ./heimdall_config:/config
    restart_policy: unless-stopped
