---
- name: Make sure the vaultwarden container is created and running
  docker_container:
    image: "vaultwarden/server:latest"
    name: "vaultwarden"
    ports:
      - 8086:80
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      WEBSOCKET_ENABLED: "true" # Enable WebSocket notifications.
    volumes:
      - "{{ data_root }}/vw_data:/data"
      - "{{ config_root }}/vaultwarden_config:/config"
    restart_policy: unless-stopped
