---
- name: Make sure the radarr container is created and running
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/radarr"
    name: "radarr"
    networks:
      - name: media_network
        ipv4_address: "{{ radarr_ip }}"
    ports:
      - 7878:7878
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - ./radarr_config:/config
      - "{{ data_root }}/media/movies:/movies"
      - "{{ data_root }}/media/anime:/anime"
      - "{{ data_root }}/media/tvshows:/tvshows"
      - "{{ data_root }}/transmission/downloads/complete:/downloads/complete"
    restart_policy: unless-stopped

