---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    nv:
      # - PUID=1000
      # - PGID=1000
      # - TZ=Europe/London
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped

# version: "3"
# services:
#   jellyfin:
#     image: jellyfin/jellyfin:latest
#     container_name: jellyfin
#     volumes:
#       - ./config:/config
#       - ./jellyfin/cache:/cache
#       - /path/to/media:/media:ro
#     restart: unless-stopped
#     deploy:
#       resources:
#         limits:
#           cpus: '2'
#           memory: 1024M
#     networks:
#       default:
#         ipv4_address: 10.10.10.14
        
# networks:
#   default:
#     external:
#       name: dockernet


# version: "3.5"
# services:
#   jellyfin:
#     image: jellyfin/jellyfin
#     container_name: jellyfin
#     # user: uid:gid
#     network_mode: "host"
#     volumes:
#       - ./config:/config
#       - ./cache:/cache
#       - ./media:/media
#       - ./media2:/media2:ro
#     restart: "unless-stopped"
#     # Optional - alternative address used for autodiscovery
#     # environment:
#       # - JELLYFIN_PublishedServerUrl=http://example.com