---
- name: utility present debian-like
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: present
  when: ansible_os_family == 'Debian'

- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "{{ permission }}"
    owner: root
    group: root

- name: mount network share
  ansible.posix.mount:
    src: "{{ mynfs }}"
    path: "{{ mountpoint }}"
    fstype: nfs
    opts: "{{ myopts }}"
    state: mounted
