---
- name: Make sure the calibre container is created and running
  docker_container:
    image: lscr.io/linuxserver/calibre:latest
    name: calibre
    networks:
      - name: media_network
    ports:
      - "8090:8080"
      - "8091:8081"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      # CLI_ARGS: #optional
      # PASSWORD: #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ config_root }}/calibre_config:/config"
      - "{{ data_root }}/media:/media"
    restart_policy: unless-stopped


