---
- name: Make sure the OpenSpeedTest container is created and running
  docker_container:
    image: openspeedtest/latest
    name: speed-test
    ports:
      - "3002:3000"
      - "3001:3001"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
