---
- name: Make sure the sonarr container is created and running
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/transmission"
    name: "transmission"
    networks:
      - name: media_network
        ipv4_address: "{{ transmission_ip }}"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - ./transmission:/config
      - "{{ data_root }}/transmission/downloads:/downloads"
    restart_policy: unless-stopped
