version: "3"

services:
  nextcloud:
    image: nextcloud:latest
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
#      - LETSENCRYPT_HOST=nextcloud.coulter.ninja
#      - VIRTUAL_HOST=nextcloud.coulter.ninja
    networks:
      - nextcloud_network
    volumes:
      - nextcloud:/var/www/html

  #mysql:
  #  image: mysql:8.0
  #  restart: unless-stopped
  #  environment:
  #    - MYSQL_DATABASE=nextcloud
  #    - MYSQL_USER=nextcloud
  #    - MYSQL_PASSWORD=nextcloud
  #    - MYSQL_ROOT_PASSWORD=nextcloud
  #  volumes:
  #    - mysql:/var/lib/mysql

  db:
    image: mariadb:latest
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    restart: unless-stopped
  
volumes:
#  mysql:
  nextcloud:
    external: true
  db:

networks:
  nextcloud_network:
    external: true

