---
- name: Make sure the audiobookshelf container is created and running
  docker_container:
    image: ghcr.io/advplyr/audiobookshelf:latest
    name: audiobookshelf
    networks:
      - name: media_network
    ports:
    ports:
      - "13378:80"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      AUDIOBOOKSHELF_UID: "99"
      AUDIOBOOKSHELF_GID: "100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ config_root }}/audiobookshelf_config:/config"
      - "{{ config_root }}/audiobookshelf_metadata:/metadata"
      - "{{ data_root }}/media:/media"
      # - </path/to/audiobooks>:/audiobooks
      # - </path/to/podcasts>:/podcasts
    restart_policy: unless-stopped
