---
# - name: Copy content of directory 'files'
#   copy:
#     src:  ../files/ #docker-compose.yml
#     dest: jellyfin # "{{ playbook_dir }}/" #/tmp/files/

# - name: Make sure that QuickSync packages are installed
#   become: yes
#   package:
#     name:
#       - vainfo
#       - intel-media-va-driver-non-free
#     state: present

- name: " {{ data_root }}/data-backup/media  sure the jellyfin container is created and running"
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/jellyfin"
    name: "jellyfin"
    # network_mode: "host"
    ports:
      - 80:8096
    # networks:
    #   - name: media_network
    #     ipv4_address: "{{ jellyfin_ip }}"
    # networks:
    #   - name: swag_internal_macvlan
    #     ipv4_address: "{{ ip_address }}"
    pull: yes
    # privileged: yes
    # devices:
    #   - "/dev/dri/renderD128:/dev/dri/renderD128"
    state: 'started'
    env:
      "DOCKER_MODS": "linuxserver/mods:jellyfin-opencl-intel"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ config_root }}/jellyfin/config:/config"
      # - "{{ data_root }}/media/tvshows:/data/tvshows"
      - "{{ data_root }}/data-backup/media:/media"
      # - "{{ data_root }}/media/movies:/data/movies"
      # - "{{ docker_dir }}/{{ container_name }}:/config"
      # - "{{ data_root }}/Media/TV:/data/TV"
      # - "{{ data_root }}_slow/Media/Transcodes:/config/data/transcodes"
      - "{{ config_root }}/jellyfin/metadata:/metadata"
      - "{{ config_root }}/jellyfin/data:/data"
      # - "{{ mergerfs_root }}/Media/Movies:/data/Movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped

