---
#         environment:
#             - OPENVPN_PROVIDER=SURFSHARK
#             - OPENVPN_CONFIG=us
#             - OPENVPN_USERNAME=user
#             - OPENVPN_PASSWORD=pass
#             - LOCAL_NETWORK=192.168.0.0/16

# sjArCtNmc7B3AyGy95ZumT   -e OPENVPN_PASSWORD=SgzKP9xRLzzEj9f6knxHc4qU   -
# e DISABLE_PORT_UPDATER=true   haugene/transmission-openvpn               


- name: Make sure the transmission vpn container is created and running
  become: yes
  docker_container:
    image: "haugene/transmission-openvpn"
    name: "transmission-openvpn"
    capabilities:
      - NET_ADMIN
    networks:
      - name: media_network
        ipv4_address: "{{ transmission_ip }}"
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    pull: yes
    restart_policy: unless-stopped
    state: 'started'
    env:
      OPENVPN_PROVIDER: SURFSHARK
      OPENVPN_CONFIG: us-dtw_udp
      OPENVPN_USERNAME: "{{ vpn_username }}"
      OPENVPN_PASSWORD: "{{ vpn_password }}"
      LOCAL_NETWORK: 192.168.0.0/16
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - ./transmission:/config
      - "{{ data_root }}/transmission/downloads:/downloads"
      # - /etc/openvpn:/etc/openvpn
      # - "{{ data_root }}:/data"
      # - /etc/openvpn/us-dtw.prod.surfshark.com_udp.ovpn:/etc/openvpn/custom/default.ovpn

