---
- name: Make sure the portainer container is created and running
  docker_container:
    image: portainer/portainer-ce
    name: portainer
    networks:
      - name: media_network
    ports:
      - "8000:8000"
      - "9000:9000"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ config_root }}/portainer_data:/data"
    restart_policy: unless-stopped
    # recreate: yes


