---
- name: utility present debian-like
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750

- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "{{ permission }}"
    owner: root
    group: docker

- name: mount network share
  ansible.posix.mount:
    src: "{{ mynfs }}"
    path: "{{ mountpoint }}"
    fstype: nfs
    opts: "{{ myopts }}"
    state: mounted

- name: check data_mountpoint exist
  ansible.builtin.file:
    path: "{{ data_mountpoint }}"
    state: directory
    mode: "{{ data_permission }}"
    owner: root
    group: docker

- name: mount data network share
  ansible.posix.mount:
    src: "{{ data_nfs }}"
    path: "{{ data_mountpoint }}"
    fstype: nfs
    opts: "{{ data_opts }}"
    state: mounted
