---
# - name: Create a homeassistant network
#   docker_network:
#     name: host
#     type: host
    # ipam_options:
      # subnet: "{{ h?omeassistant_subnet }}"

- name: Make sure the {{ container_name }} container is created and running
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "homeassistant/home-assistant:stable"
    network_mode: host
    devices:
      - "/dev/zigbee:/dev/zigbee"
      - "/dev/zwave:/dev/zwave"
    # networks:
    # - name: host
    # image: "homeassistant/home-assistant:stable"
    # networks:
      # - name: homeassistant_network
        # ipv4_address: "{{ homeassistant_ip }}"
    pull: yes
    state: 'started'
    # ports:
    #   - "8123:8123"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ data_root }}/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    state: 'started'
    restart_policy: unless-stopped

# version: '3'
# services:
#   homeassistant:
#     volumes:
#     privileged: true
