---
- name: Make sure the plex container is created and running
  become: yes
  docker_container:
    image: "ghcr.io/linuxserver/plex:latest"
    name: "plex"
    ports:
      - 32400:32400
    networks:
      - name: media_network
        ipv4_address: "{{ plex_ip }}"
    # networks:
    #   - name: swag_internal_macvlan
    #     ipv4_address: "{{ ip_address }}"
    pull: yes
    # privileged: yes
    devices:
      /dev/dri:/dev/dri
    #   - "/dev/dri/renderD128:/dev/dri/renderD128"
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      "VERSION": docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ./plex_config:/config
      # - "{{ data_root }}/tvshows:/data/tvshows"
      - "{{ data_root }}/media/anime:/data/anime"
      - "{{ data_root }}/media/tvshows:/data/tv"
      - "{{ data_root }}/media/movies:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
